---
# Preamble

## Author
author:
  name: Зиязетдинов Алмаз
  degrees: DSc
  orcid: 0000-0002-0877-7063
  email: kulyabov-ds@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6
## Title
title: "Шаблон отчёта по лабораторной работе"
subtitle: "Простейший вариант"
license: "CC BY"
## Generic options
lang: ru-RU
number-sections: true
toc: true
toc-title: "Содержание"
toc-depth: 2
## Crossref customization
crossref:
  lof-title: "Список иллюстраций"
  lot-title: "Список таблиц"
  lol-title: "Листинги"
## Bibliography
bibliography:
  - bib/cite.bib
csl: _resources/csl/gost-r-7-0-5-2008-numeric.csl
format:
## Pdf output format
  pdf:
    toc: true
    number-sections: true
    colorlinks: false
    toc-depth: 2
    lof: true # List of figures
    lot: true # List of tables
### Document
    documentclass: scrreprt
    papersize: a4
    fontsize: 12pt
    linestretch: 1.5
### Language
    babel-lang: russian
    babel-otherlangs: english
### Biblatex
    cite-method: biblatex
    biblio-style: gost-numeric
    biblatexoptions:
      - backend=biber
      - langhook=extras
      - autolang=other*
### Misc options
    csquotes: true
    indent: true
    header-includes: |
      \usepackage{indentfirst}
      \usepackage{float}
      \floatplacement{figure}{H}
      \usepackage[math,RM={Scale=0.94},SS={Scale=0.94},SScon={Scale=0.94},TT={Scale=MatchLowercase,FakeStretch=0.9},DefaultFeatures={Ligatures=Common}]{plex-otf}
## Docx output format
  docx:
    toc: true
    number-sections: true
    toc-depth: 2
---

# Цель работы

Цель работы:
Настроить динамическую организации.
Выполнение работы:
Теперь откроем проект с названием lab_PT-14.pkt и сохраним под названием
lab_PT-15.pkt. После чего откроем его для дальнейшего редактирования 
Рис. 1.1. Открытие проекта lab_PT-15.pkt.
Для начала настроим OSPF на маршрутизаторе msk-donskaya-gw-
1 Включение OSPF на маршрутизаторе предполагает, во-первых, включение
процесса OSPF командой router ospf, во-вторых — назначение областей (зон)
интерфейсам с помощью команды network area (Рис. 1.2).
Идентификатор процесса OSPF (process-id) по сути идентифицирует
маршрутизатор в автономной системе, и, вообще говоря, он не должен совпадать
с идентификаторами процессов на других маршрутизаторах.
Значение идентификатора области (area-id) может быть целым числом от 0
до 4294967295 или может быть представлено в виде IP-адреса: A.B.C.D. Область
0 называется магистралью, области с другими идентификаторами должны
подключаться к магистрали.


::: {#refs}
:::
