---
# Preamble

## Author
author:
  name: Зиязетдинов Алмаз Радикович
  degrees: DSc
  orcid: 0000-0002-0877-7063
  email: 1132222010@pfur.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6
## Title
title: "Отчёт по лабораторной работе №1"
license: "CC BY"
## Generic options
lang: ru-RU
number-sections: true
toc: true
toc-title: "Содержание"
toc-depth: 2
## Crossref customization
crossref:
  lof-title: "Список иллюстраций"
  lot-title: "Список таблиц"
  lol-title: "Листинги"
## Bibliography
bibliography:
  - bib/cite.bib
csl: _resources/csl/gost-r-7-0-5-2008-numeric.csl
format:
## Pdf output format
  pdf:
    toc: true
    number-sections: true
    colorlinks: false
    toc-depth: 2
    lof: true # List of figures
    lot: true # List of tables
### Document
    documentclass: scrreprt
    papersize: a4
    fontsize: 12pt
    linestretch: 1.5
### Language
    babel-lang: russian
    babel-otherlangs: english
### Biblatex
    cite-method: biblatex
    biblio-style: gost-numeric
    biblatexoptions:
      - backend=biber
      - langhook=extras
      - autolang=other*
### Misc options
    csquotes: true
    indent: true
    header-includes: |
      \usepackage{indentfirst}
      \usepackage{float}
      \floatplacement{figure}{H}
      \usepackage[math,RM={Scale=0.94},SS={Scale=0.94},SScon={Scale=0.94},TT={Scale=MatchLowercase,FakeStretch=0.9},DefaultFeatures={Ligatures=Common}]{plex-otf}
## Docx output format
  docx:
    toc: true
    number-sections: true
    toc-depth: 2
---

# Цель работы

Установка инструмента моделирования конфигурации сети Cisco Packet
Tracer [3], знакомство с его интерфейсом.

# Задание

1. Установить на домашнем устройстве Cisco Packet Tracer.
2. Постройте простейшую сеть в Cisco Packet Tracer, проведите простейшую
настройку оборудования.

# Последовательность выполнения работы

    1. Установите в вашей операционной системе Cisco Packet Tracer     ([рис.1 @fig-001]).                                                                 |

 Построение простейшей сети
1. Создайте новый проект (например, lab_PT-01.pkt).
2. В рабочем пространстве разместите концентратор (Hub-PT) и четыре оконечных устройства PC. Соедините оконечные устройства с концентратором
прямым кабелем  Щёлкнув последовательно на каждом оконечном устройстве, задайте статические IP-адреса 192.168.1.11, 192.168.1.12,
192.168.1.13, 192.168.1.14 с маской подсети 255.255.255.0 

Модель простой сети с концентратором ([рис.2 @fig-001]).                                                                 |

3. В основном окне проекта перейдите из режима реального времени (Realtime)
в режим моделирования (Simulation). Выберите на панели инструментов
мышкой «Add Simple PDU (P)» и щёлкните сначала на PC0, затем на PC2.
В рабочей области должны будут появится два конверта, обозначающих пакеты, в списке событий на панели моделирования должны будут появиться
два события, относящихся к пакетам ARP и ICMP соответственно (рис. 1.5).
На панели моделирования нажмите кнопку «Play» и проследите за движением пакетов ARP и ICMP от устройства PC0 до устройства PC2 и обратно.

Простейшая модель сети    ([рис.4 @fig-004]).  
4. Щёлкнув на строке события, откройте окно информации о PDU и изучите,
что происходит на уровне модели OSI при перемещении пакета (рис. 1.6).
Используя кнопку «Проверь себя» (Challenge Me) на вкладке OSI Model,
ответьте на вопросы.
5. Откройте вкладку с информацией о PDU (рис. 1.7). Исследуйте структуру
пакета ICMP. Опишите структуру кадра Ethernet. Какие изменения происходят в кадре Ethernet при передвижении пакета? Какой тип имеет кадр
Ethernet? Опишите структуру MAC-адресов.
6. Очистите список событий, удалив сценарий моделирования. Выберите на
панели инструментов мышкой «Add Simple PDU (P)» и щёлкните сначала
на PC0, затем на PC2. Снова выберите на панели инструментов мышкой
«Add Simple PDU (P)» и щёлкните сначала на PC2, затем на PC0. На панели
моделирования нажмите кнопку «Play» и проследите за возникновением
коллизии (рис. 1.8). В списке событий посмотрите информацию о PDU.
В отчёте поясните, как отображается в заголовках пакетов информация
о коллизии и почему возникла коллизия.

События в режиме моделирования Packet Tracer([рис.3 @fig-003]).        



7. Перейдите в режим реального времени (Realtime). В рабочем пространстве
разместите коммутатор (например Cisco 2950-24) и 4 оконечных устройства
PC. Соедините оконечные устройства с коммутатором прямым кабелем.
Щёлкнув последовательно на каждом оконечном устройстве, задайте статические IP-адреса 192.168.1.21, 192.168.1.22, 192.168.1.23, 192.168.1.24 с маской
подсети 255.255.255.0.
8. В основном окне проекта перейдите из режима реального времени (Realtime)
в режим моделирования (Simulation). Выберите на панели инструментов
мышкой «Add Simple PDU (P)» и щёлкните сначала на PC4, затем на PC6.
В рабочей области должны будут появится два конверта, обозначающих
пакеты, в списке событий на панели моделирования должны будут появиться два события, относящихся к пакетам ARP и ICMP соответственно
 
События в режиме моделирования Packet Tracer ([рис.5 @fig-005]). 
(рис. 1.9). На панели моделирования нажмите кнопку «Play» и проследите
за движением пакетов ARP и ICMP от устройства PC4 до устройства PC6
и обратно. В отчёте поясните, есть ли различия и в чём они заключаются
в событиях протокола ARP в сценарии с концентратором.

Модель простой сети с коммутатором([рис.6 @fig-006]).  

                                                        |
9. Исследуйте структуру пакета ICMP. Опишите структуру кадра Ethernet.
Какие изменения происходят в кадре Ethernet при передвижении пакета?
Какой тип имеет кадр Ethernet? Опишите структуру MAC-адресов.
10. Очистите список событий, удалив сценарий моделирования. Выберите на
панели инструментов мышкой «Add Simple PDU (P)» и щёлкните сначала
на PC4, затем на PC6. Снова выберите на панели инструментов мышкой
«Add Simple PDU (P)» и щёлкните сначала на PC6, затем на PC4. На
панели моделирования нажмите кнопку «Play» и проследите за движением
пакетов. В отчёте поясните, почему не возникает коллизия.
11. Перейдите в режим реального времени (Realtime). В рабочем пространстве соедините кроссовым кабелем концентратор и коммутатор. Перейдите
в режим моделирования (Simulation). Очистите список событий, удалив
сценарий моделирования. Выберите на панели инструментов мышкой «Add Simple PDU (P)» и щёлкните сначала на PC0, затем на PC4. Снова выберите на панели инструментов мышкой «Add Simple PDU (P)» и щёлкните
сначала на PC4, затем на PC0. На панели моделирования нажмите кнопку
«Play» и проследите за движением пакетов. В отчёте поясните, почему
сначала возникает коллизия (рис. 1.10), а затем пакеты успешно достигают
пункта назначения.

12. Очистите список событий, удалив сценарий моделирования. На панели
моделирования нажмите «Play» и в списке событий получите пакеты STP
(рис. 1.11). Исследуйте структуру STP. Опишите структуру кадра Ethernet
в этих пакетах. Какой тип имеет кадр Ethernet? Опишите структуру MACадресов.
13. Перейдите в режим реального времени (Realtime). В рабочем пространстве добавьте маршрутизатор (например, Cisco 2811). Соедините прямым
кабелем коммутатор и маршрутизатор (рис. 1.12). Щёлкните на маршрутизаторе и на вкладке его конфигурации пропишите статический IP-адрес
192.168.1.254 с маской 255.255.255.0, активируйте порт, поставив галочку
«On» напротив «Port Status» (рис. 1.13).
14. Перейдите в режим моделирования (Simulation). Очистите список событий, удалив сценарий моделирования. Выберите на панели инструментов
мышкой «Add Simple PDU (P)» и щёлкните сначала на PC3, затем на маршрутизаторе. На панели моделирования нажмите кнопку «Play» и проследите
за движением пакетов ARP, ICMP, STP и CDP. Исследуйте структуру пакета CDP, опишите структуру кадра Ethernet. Какой тип имеет кадр Ethernet?
Опишите структуру MAC-адресов.


Модель простой сети с  маршрутизатором([рис.7 @fig-007]).  
Сценарий с протоколом STP ([рис.8 @fig-008]).  


# Выводы
Вывод:
В ходе выполнения лабораторной работы мы научились устанавливать
инструмент моделирования конфигурации сети Cisco Packet Tracer без учётной
записи и познакомились с его интерфейсом.





# Ответы на контрольные вопросы:
1 Дайте определение следующим понятиям: концентратор, коммутатор,
маршрутизатор, шлюз (gateway). В каких случаях следует использовать
тот или иной тип сетевого оборудования?
Концентратор (Hub): концентратор является устройством, которое
принимает данные с одного устройства сети и передает их всем
остальным устройствам в сети.
Он работает на физическом уровне модели OSI (Open Systems
Interconnection), просто усиливая сигнал и передавая его по всем
портам.
Концентратор не имеет интеллекта для анализа данных или
управления трафиком.
Обычно используется в небольших сетях или для расширения
количества портов в сети.
Коммутатор (Switch): коммутатор также работает на канальном
уровне OSI и способен анализировать адреса MAC (Media Access
Control) устройств, подключенных к нему.
В отличие от концентратора, коммутатор передает данные только
тому устройству, для которого они предназначены, что делает его
более эффективным по сравнению с концентратором.



::: {#refs}
:::
